name: Telegram Bot
on:
  schedule:
    - cron: '*/5 * * * *' # Every 5 minutes
jobs:
  job:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Check Tickets
        uses: appleboy/telegram-action@master
        with:
          product-id: 212702
          schedule-id: 100001
          seat-id: 1_0
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: '有票了 快搶!'
